### ISSUE TITLE
feature request - context for react without using react-router

### ISSUE THREAD

**Issue by flyfishMT** [HipsterBrown/robo-wizard#32]
Just an idea - it would be great if the context functionality and hooks that are in the react-router could be refactored and available also without having to use a routed version.  So you could break your Steps up into separate files and get the context, but they didn't have to be "Routes".  The visibility of the Step could be the responsibility of the App or builtin?

```
import { useWizardContext } from '@robo-wizard/react';
export const Step1 = () => 
  const wizard = useWizardContext();
  ...
}
export const App = () => {
  return (
    <Wizard>
      <Step1 />
      <Step2 />
   </Wizard>
  );
}
```

The useWizard hook for @robo-wizard/react almost works to accomplish this in child components, but it errors when no steps are provided.  Otherwise the consumer App has to pass everything down through props or implement its own context.

It's not much different than the routed version but my parent app already uses react-router 5,  not sure if I'll have conflicts.

Thanks, again - awesome library.

**Comment by HipsterBrown** [comment]
This does seem like a logical addition to the `@robo-wizard/react` package, and it could be reused by the react-router package since the Provider just holds the `wizard` object from the `useWizard` hook. 

My only concern is API confusion between the react and react-router packages. As you stated, the react package doesn't provide any options about conditionally displaying steps; the react-router package hands that responsibility off to the`useRoutes` hook. 

I'll need to think a bit about how to add that capability. I'm also open to pull requests.

The initial (naive) approach might be something like:

```tsx
const WizardContext = React.createContext(null);

function Step (props) {}

function Wizard({ children, initialValues }) {
  const steps = Children.map(children, child => child.type === Step ? child.props : null)?.filter(Boolean) ?? [];
  const wizard = useWizard(steps, initialValues);
  const step = steps.find(({ name }) => name === wizard.currentStep);

  return (
    <WizardContext.Provider value={wizard}>
      {step.element}
    </WizardContext.Provider>
  );
}

function useWizardContext () {
  return useContext(WizardContext);
}
```

> It's not much different than the routed version but my parent app already uses react-router 5, not sure if I'll have conflicts.

There will certainly be conflicts due to the breaking changes between v5 and v6 of `react-router` 😞

**Comment by flyfishMT** [comment]
I like the idea of a <Steps> container so that other elements can use the context without being type Step.  Then the Step components also wouldn't necessarily have to be type Step, they could be anything?

```
<Wizard>
 <Progress />
  <Steps>
    <Step1 />
    <Step2 />
  </Steps>
  <Another />
</Wizard>
```

I could be open to a PR **attempt** :) but would want to know how you wanted your package libraries APIs to look because of  any API confusion like you say.

**Comment by HipsterBrown** [comment]
@flyfishMT I drafted an initial PR with an example project. While potentially confusing, I think the upgrade path from "in-memory" to a "routed" Wizard is kind of neat by mostly changing the imported package. 

The proposed implementation will only display the current step based on the initial child Step components, so the `Progress` and `Another` components from the above example would need to go into some kind of layout component within each Step.

**Comment by flyfishMT** [comment]
@HipsterBrown - very nice!  I would still love the Steps container, but maybe I'm not understanding a layout component.  I was thinking, it could be optional. If first child of Wizard is Steps container component, Wizard would render all children and Steps wold render only current Step, otherwise work as is with Wizard rendering current Step.  But I understand what you are doing keeping it consistent with react-router version - that is pretty neat.
